// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/accesscontrol_x/acl.proto

package types

import (
	fmt "fmt"
	accesscontrol "github.com/cosmos/cosmos-sdk/types/accesscontrol"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgUpdateResourceDependencyMappingProposal struct {
	Title                    string                                   `protobuf:"bytes,1,opt,name=title,proto3" json:"title" yaml:"title"`
	Description              string                                   `protobuf:"bytes,2,opt,name=description,proto3" json:"description" yaml:"description"`
	MessageDependencyMapping []accesscontrol.MessageDependencyMapping `protobuf:"bytes,3,rep,name=message_dependency_mapping,json=messageDependencyMapping,proto3" json:"message_dependency_mapping" yaml:"message_dependency_mapping"`
	Operator                 string                                   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator" yaml:"operator"`
}

func (p *MsgUpdateResourceDependencyMappingProposal) String() string {
	return proto.CompactTextString(p)
}

func (m *MsgUpdateResourceDependencyMappingProposal) Reset() {
	*m = MsgUpdateResourceDependencyMappingProposal{}
}
func (*MsgUpdateResourceDependencyMappingProposal) ProtoMessage() {}
func (*MsgUpdateResourceDependencyMappingProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c068418a437f4b, []int{0}
}
func (m *MsgUpdateResourceDependencyMappingProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateResourceDependencyMappingProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateResourceDependencyMappingProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateResourceDependencyMappingProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateResourceDependencyMappingProposal.Merge(m, src)
}
func (m *MsgUpdateResourceDependencyMappingProposal) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateResourceDependencyMappingProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateResourceDependencyMappingProposal.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateResourceDependencyMappingProposal proto.InternalMessageInfo

type MsgUpdateResourceDependencyMappingProposalJsonFile struct {
	Title                    string                                   `protobuf:"bytes,1,opt,name=title,proto3" json:"title" yaml:"title"`
	Description              string                                   `protobuf:"bytes,2,opt,name=description,proto3" json:"description" yaml:"description"`
	Deposit                  string                                   `protobuf:"bytes,3,opt,name=deposit,proto3" json:"deposit" yaml:"deposit"`
	MessageDependencyMapping []accesscontrol.MessageDependencyMapping `protobuf:"bytes,4,rep,name=message_dependency_mapping,json=messageDependencyMapping,proto3" json:"message_dependency_mapping" yaml:"message_dependency_mapping"`
}

func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) Reset() {
	*m = MsgUpdateResourceDependencyMappingProposalJsonFile{}
}
func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) String() string {
	return proto.CompactTextString(m)
}
func (*MsgUpdateResourceDependencyMappingProposalJsonFile) ProtoMessage() {}
func (*MsgUpdateResourceDependencyMappingProposalJsonFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c068418a437f4b, []int{1}
}
func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateResourceDependencyMappingProposalJsonFile.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateResourceDependencyMappingProposalJsonFile.Merge(m, src)
}
func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateResourceDependencyMappingProposalJsonFile.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateResourceDependencyMappingProposalJsonFile proto.InternalMessageInfo

func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) GetDeposit() string {
	if m != nil {
		return m.Deposit
	}
	return ""
}

func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) GetMessageDependencyMapping() []accesscontrol.MessageDependencyMapping {
	if m != nil {
		return m.MessageDependencyMapping
	}
	return nil
}

type MsgUpdateResourceDependencyMappingProposalResponse struct {
}

func (m *MsgUpdateResourceDependencyMappingProposalResponse) Reset() {
	*m = MsgUpdateResourceDependencyMappingProposalResponse{}
}
func (m *MsgUpdateResourceDependencyMappingProposalResponse) String() string {
	return proto.CompactTextString(m)
}
func (*MsgUpdateResourceDependencyMappingProposalResponse) ProtoMessage() {}
func (*MsgUpdateResourceDependencyMappingProposalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c068418a437f4b, []int{2}
}
func (m *MsgUpdateResourceDependencyMappingProposalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateResourceDependencyMappingProposalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateResourceDependencyMappingProposalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateResourceDependencyMappingProposalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateResourceDependencyMappingProposalResponse.Merge(m, src)
}
func (m *MsgUpdateResourceDependencyMappingProposalResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateResourceDependencyMappingProposalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateResourceDependencyMappingProposalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateResourceDependencyMappingProposalResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateResourceDependencyMappingProposal)(nil), "cosmos.accesscontrol.v1beta1.MsgUpdateResourceDependencyMappingProposal")
	proto.RegisterType((*MsgUpdateResourceDependencyMappingProposalJsonFile)(nil), "cosmos.accesscontrol.v1beta1.MsgUpdateResourceDependencyMappingProposalJsonFile")
	proto.RegisterType((*MsgUpdateResourceDependencyMappingProposalResponse)(nil), "cosmos.accesscontrol.v1beta1.MsgUpdateResourceDependencyMappingProposalResponse")
}

func init() { proto.RegisterFile("cosmos/accesscontrol_x/acl.proto", fileDescriptor_74c068418a437f4b) }

var fileDescriptor_74c068418a437f4b = []byte{
	// 467 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x93, 0x3d, 0x8b, 0xd4, 0x5e,
	0x14, 0xc6, 0x93, 0x7f, 0xf6, 0xef, 0x4b, 0x56, 0x54, 0x82, 0x45, 0x1c, 0x34, 0x77, 0x0c, 0x0a,
	0xa3, 0x60, 0xc2, 0x8e, 0xa2, 0xb0, 0x76, 0x83, 0x28, 0x88, 0x03, 0x12, 0xb0, 0xb1, 0x19, 0xee,
	0xdc, 0x1c, 0x62, 0x30, 0xc9, 0xb9, 0xe4, 0xdc, 0x95, 0x9d, 0xce, 0x52, 0x3b, 0x3b, 0xed, 0x9c,
	0x8f, 0xb3, 0xe5, 0x96, 0x16, 0x72, 0x91, 0x99, 0x46, 0xa6, 0xcc, 0x27, 0x10, 0x73, 0x77, 0x86,
	0x59, 0xdd, 0xf5, 0xa5, 0xda, 0x2a, 0xc9, 0xef, 0x3e, 0xe7, 0xb9, 0xe7, 0xe4, 0xe1, 0xb8, 0x5d,
	0x81, 0x54, 0x22, 0xc5, 0x5c, 0x08, 0x20, 0x12, 0x58, 0xa9, 0x1a, 0x8b, 0xd1, 0x6e, 0xcc, 0x45,
	0x11, 0xc9, 0x1a, 0x15, 0x7a, 0x57, 0x8c, 0x22, 0x3a, 0xa4, 0x88, 0x5e, 0x6f, 0x8d, 0x41, 0xf1,
	0xad, 0xce, 0xa5, 0x0c, 0x33, 0x6c, 0x85, 0xf1, 0x8f, 0x37, 0x53, 0xd3, 0xb9, 0x7e, 0x94, 0x6b,
	0x2c, 0xb0, 0x22, 0xc5, 0x2b, 0x45, 0x07, 0xaa, 0xde, 0x91, 0xaa, 0xc3, 0xf7, 0xb4, 0xca, 0xf0,
	0x83, 0xe3, 0xde, 0x1a, 0x52, 0xf6, 0x5c, 0xa6, 0x5c, 0x41, 0x02, 0x84, 0x3b, 0xb5, 0x80, 0x87,
	0x20, 0xa1, 0x4a, 0xa1, 0x12, 0x93, 0x21, 0x97, 0x32, 0xaf, 0xb2, 0x67, 0x35, 0x4a, 0x24, 0x5e,
	0x78, 0xb1, 0xfb, 0xbf, 0xca, 0x55, 0x01, 0xbe, 0xdd, 0xb5, 0x7b, 0x67, 0x07, 0x97, 0x17, 0x9a,
	0x19, 0xd0, 0x68, 0x76, 0x6e, 0xc2, 0xcb, 0x62, 0x3b, 0x6c, 0x3f, 0xc3, 0xc4, 0x60, 0xef, 0xb1,
	0xbb, 0x99, 0x02, 0x89, 0x3a, 0x97, 0x2a, 0xc7, 0xca, 0xff, 0xaf, 0x2d, 0xbb, 0xb1, 0xd0, 0x6c,
	0x1d, 0x37, 0x9a, 0x79, 0xa6, 0x78, 0x0d, 0x86, 0xc9, 0xba, 0xc4, 0xfb, 0x64, 0xbb, 0x9d, 0x12,
	0x88, 0x78, 0x06, 0xa3, 0x74, 0xd5, 0xdf, 0xa8, 0x34, 0x0d, 0xfa, 0x4e, 0xd7, 0xe9, 0x6d, 0xf6,
	0xef, 0x45, 0xbf, 0xfb, 0xa5, 0xd1, 0xd0, 0xd4, 0xff, 0x32, 0xde, 0xe0, 0xe6, 0x9e, 0x66, 0x56,
	0xa3, 0xd9, 0x35, 0xd3, 0xc5, 0xf1, 0xf7, 0x84, 0x89, 0x5f, 0x1e, 0x63, 0xe2, 0x3d, 0x70, 0xcf,
	0xa0, 0x84, 0x9a, 0x2b, 0xac, 0xfd, 0x8d, 0x76, 0x4e, 0xb6, 0xd0, 0x6c, 0xc5, 0x1a, 0xcd, 0x2e,
	0x18, 0xfb, 0x25, 0x09, 0x93, 0xd5, 0xe1, 0xf6, 0xc5, 0xb7, 0x53, 0x66, 0x7d, 0x9c, 0x32, 0xeb,
	0xdb, 0x94, 0x59, 0x6f, 0xbe, 0x74, 0xad, 0xf0, 0x9d, 0xe3, 0xf6, 0xff, 0x3e, 0x99, 0x27, 0x84,
	0xd5, 0xa3, 0xbc, 0x80, 0x13, 0x4c, 0xe8, 0xbe, 0x7b, 0x3a, 0x05, 0x89, 0x94, 0x2b, 0xdf, 0x69,
	0x4d, 0xae, 0x2e, 0x34, 0x5b, 0xa2, 0x46, 0xb3, 0xf3, 0x4b, 0x83, 0x16, 0x84, 0xc9, 0xf2, 0xe8,
	0x4f, 0xd1, 0x6e, 0x9c, 0x78, 0xb4, 0xe1, 0xdd, 0x7f, 0x89, 0x22, 0x01, 0x92, 0x58, 0x11, 0x0c,
	0x9e, 0xee, 0xcd, 0x02, 0x7b, 0x7f, 0x16, 0xd8, 0x5f, 0x67, 0x81, 0xfd, 0x7e, 0x1e, 0x58, 0xfb,
	0xf3, 0xc0, 0xfa, 0x3c, 0x0f, 0xac, 0x17, 0xfd, 0x2c, 0x57, 0x2f, 0x77, 0xc6, 0x91, 0xc0, 0x32,
	0x3e, 0x58, 0x55, 0xf3, 0xb8, 0x4d, 0xe9, 0xab, 0x78, 0xf7, 0xa7, 0xbd, 0x55, 0x13, 0x09, 0x34,
	0x3e, 0xd5, 0x2e, 0xec, 0x9d, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0x84, 0xb6, 0x20, 0x70, 0x58,
	0x04, 0x00, 0x00,
}

func (m *MsgUpdateResourceDependencyMappingProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateResourceDependencyMappingProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateResourceDependencyMappingProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintAcl(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.MessageDependencyMapping) > 0 {
		for iNdEx := len(m.MessageDependencyMapping) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MessageDependencyMapping[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAcl(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintAcl(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintAcl(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MessageDependencyMapping) > 0 {
		for iNdEx := len(m.MessageDependencyMapping) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MessageDependencyMapping[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAcl(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Deposit) > 0 {
		i -= len(m.Deposit)
		copy(dAtA[i:], m.Deposit)
		i = encodeVarintAcl(dAtA, i, uint64(len(m.Deposit)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintAcl(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintAcl(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateResourceDependencyMappingProposalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateResourceDependencyMappingProposalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateResourceDependencyMappingProposalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintAcl(dAtA []byte, offset int, v uint64) int {
	offset -= sovAcl(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateResourceDependencyMappingProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovAcl(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovAcl(uint64(l))
	}
	if len(m.MessageDependencyMapping) > 0 {
		for _, e := range m.MessageDependencyMapping {
			l = e.Size()
			n += 1 + l + sovAcl(uint64(l))
		}
	}
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovAcl(uint64(l))
	}
	return n
}

func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovAcl(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovAcl(uint64(l))
	}
	l = len(m.Deposit)
	if l > 0 {
		n += 1 + l + sovAcl(uint64(l))
	}
	if len(m.MessageDependencyMapping) > 0 {
		for _, e := range m.MessageDependencyMapping {
			l = e.Size()
			n += 1 + l + sovAcl(uint64(l))
		}
	}
	return n
}

func (m *MsgUpdateResourceDependencyMappingProposalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovAcl(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAcl(x uint64) (n int) {
	return sovAcl(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateResourceDependencyMappingProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAcl
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateResourceDependencyMappingProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateResourceDependencyMappingProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAcl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAcl
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAcl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAcl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAcl
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAcl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageDependencyMapping", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAcl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAcl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAcl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageDependencyMapping = append(m.MessageDependencyMapping, accesscontrol.MessageDependencyMapping{})
			if err := m.MessageDependencyMapping[len(m.MessageDependencyMapping)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAcl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAcl
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAcl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAcl(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAcl
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAcl
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateResourceDependencyMappingProposalJsonFile: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateResourceDependencyMappingProposalJsonFile: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAcl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAcl
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAcl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAcl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAcl
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAcl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deposit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAcl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAcl
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAcl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Deposit = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageDependencyMapping", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAcl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAcl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAcl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageDependencyMapping = append(m.MessageDependencyMapping, accesscontrol.MessageDependencyMapping{})
			if err := m.MessageDependencyMapping[len(m.MessageDependencyMapping)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAcl(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAcl
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateResourceDependencyMappingProposalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAcl
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateResourceDependencyMappingProposalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateResourceDependencyMappingProposalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipAcl(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAcl
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAcl(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAcl
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAcl
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAcl
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAcl
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAcl
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAcl
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAcl        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAcl          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAcl = fmt.Errorf("proto: unexpected end of group")
)
