// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/crypto/gmssl/keys.proto

package gmssl

import (
	// fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	gmssl "github.com/tendermint/tendermint/crypto/gmssl"
)

// Reference imports to suppress errors if they are not otherwise used.

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Expected:

// PubKey defines a gmssl public key
// Key is the compressed form of the pubkey. The first byte depends is a 0x02 byte
// if the y-coordinate is the lexicographically largest of the two associated with
// the x-coordinate. Otherwise the first byte is a 0x03.
// This prefix is followed with the x-coordinate.
type PubKey struct {
	Key *gmssl.PublicKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

type PrivKey struct {
	Key *gmssl.PrivateKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

